"""Routes: /api/run (SSE stream) + pipeline/executor runner helpers."""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Literal

from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from voly.correlation import ensure_correlation_id, get_correlation_id
from voly.executor.base import executor_failure_details

router = APIRouter()
# Executor calls are blocking (subprocess.run) but I/O-bound, not CPU-bound —
# a small fixed pool queued concurrent /api/run requests invisibly behind
# whatever was already running. VOLY_RUN_POOL_WORKERS lets deployments size
# it to their concurrency needs.
_THREAD_POOL = ThreadPoolExecutor(
    max_workers=int(os.environ.get("VOLY_RUN_POOL_WORKERS", "16"))
)
# How often to send an SSE heartbeat while waiting on the blocking call —
# keeps proxies/browsers from idling out the connection during a long queue
# wait or a long-running executor, same pattern as /api/tasks/stream.
_RUN_HEARTBEAT_SECONDS = 15
_log = logging.getLogger("voly.web.run")

# Code extensions to search when gathering context
_CODE_EXTS = ("*.py", "*.ts", "*.tsx", "*.js", "*.jsx", "*.go", "*.rs", "*.cs", "*.java", "*.asmdef")

# Common English/Russian stop-words to skip during keyword extraction
_STOP_WORDS = frozenset({
    "the", "for", "and", "this", "that", "with", "from", "have", "будет", "нужно",
    "надо", "чтобы", "тебе", "тест", "создай", "напиши", "добавь", "сделай",
    "test", "add", "create", "make", "write", "function", "class", "file",
    "import", "return", "async", "await", "true", "false", "none",
})


class RunRequest(BaseModel):
    task: str
    agent: str = ""
    model: str = ""
    executor: str = "pipeline"
    cwd: str = ""
    max_turns: int = 30
    # Total executor deadline in seconds, incl. internal model-fallback loops.
    timeout: int = 300
    a2a_delegate: bool = False
    # Run the executor but roll back all file changes afterwards; the diff
    # preview lands in result metadata (executor safety policy).
    dry_run: bool = False
    # User-confirmed tech stack from TechSelectionModal.
    # Each entry: {name, label, version, category, notes?}
    tech_stack: list[dict] = []
    # Explicit bounded workflow. Empty preserves existing dispatch behavior.
    workflow: Literal["", "review-until-clean"] = ""
    max_rounds: int = 3
    deadline_seconds: float = 900.0


class TechDetectRequest(BaseModel):
    task: str
    cwd: str = ""


class PreflightRequest(BaseModel):
    tech: list[str]  # registry names to check


# Only language/infra runtimes have system-level binaries worth checking.
# Framework packages (fastapi, react, etc.) are installed via package managers.
_RUNTIME_BINS: dict[str, str] = {
    "python": "python3",
    "node": "node",
    "docker": "docker",
    "unity": "unity",  # Unity Hub CLI or Editor symlink in PATH
}


def _sse(event_type: str, data: dict[str, Any]) -> str:
    return f"data: {json.dumps({'type': event_type, **data})}\n\n"


# ── Greenfield scaffolding ────────────────────────────────────────────────────

def _gitignore_for_stack(tech_stack: list[dict]) -> str:
    names = {t.get("name", "") for t in tech_stack}
    lines = ["# Generated by VOLY greenfield scaffolding"]
    if names & {"python", "fastapi", "django", "flask", "pygame", "pytest", "pydantic", "uvicorn"}:
        lines += ["", "__pycache__/", "*.py[cod]", ".venv/", "venv/", "dist/", "*.egg-info/", ".pytest_cache/"]
    if names & {"node", "typescript", "react", "svelte", "sveltekit", "vue", "nextjs", "phaser", "vite"}:
        lines += ["", "node_modules/", "dist/", ".next/", "build/", ".svelte-kit/", "*.local"]
    if names & {"unity", "csharp"}:
        lines += ["", "[Ll]ibrary/", "[Tt]emp/", "[Oo]bj/", "[Bb]uild/", "[Bb]uilds/",
                  "[Ll]ogs/", "[Uu]ser[Ss]ettings/", "*.csproj.user"]
    if names & {"godot"}:
        lines += ["", ".godot/", "*.translation", "export_presets.cfg"]
    lines += ["", ".env", ".env.local", "*.log"]
    return "\n".join(lines) + "\n"


def _scaffold_greenfield(work_dir: str, tech_stack: list[dict]) -> bool:
    """Create project dir + git init if work_dir does not exist. Returns True if scaffolded."""
    if os.path.isdir(work_dir):
        return False
    _log.info("[GREENFIELD] creating project dir: %s", work_dir)
    os.makedirs(work_dir, exist_ok=True)
    subprocess.run(["git", "init"], cwd=work_dir, capture_output=True, text=True)
    with open(os.path.join(work_dir, ".gitignore"), "w", encoding="utf-8") as f:
        f.write(_gitignore_for_stack(tech_stack))
    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "voly", "GIT_AUTHOR_EMAIL": "voly@localhost",
        "GIT_COMMITTER_NAME": "voly", "GIT_COMMITTER_EMAIL": "voly@localhost",
    }
    subprocess.run(["git", "add", ".gitignore"], cwd=work_dir, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", "chore: init project (voly greenfield)"],
        cwd=work_dir, capture_output=True, env=env,
    )
    return True


# ── Auto-reuse pre-stage ─────────────────────────────────────────────────────

def _run_auto_reuse(task: str, cwd: str, config: Any) -> None:
    """Search GitHub for similar repos and save a reuse report before executor runs.

    No-op when reuse.auto is false, cwd is empty, or any error occurs.
    The saved report is picked up automatically by _gather_local_context via context.py.
    """
    if not cwd:
        return
    try:
        from voly.reuse.pipeline import auto_reuse
        auto_reuse(task, cwd=cwd, config=config)
    except Exception:
        pass


# ── Local context gathering ───────────────────────────────────────────────────

def _gather_local_context(task: str, cwd: str, max_chars: int = 6000) -> str:
    """Find and read local files relevant to the task. Returns a compact context block."""
    cwd = os.path.expanduser(cwd)
    if not os.path.isdir(cwd):
        return ""

    parts: list[str] = []
    total = 0

    # Optional: inject latest voly reuse report (thin PR3 hook — not a full search stage).
    try:
        from voly.reuse.context import format_reuse_context

        reuse_block = format_reuse_context(cwd, max_chars=min(1500, max_chars // 3))
        if reuse_block:
            parts.append(reuse_block + "\n")
            total += len(reuse_block)
    except Exception:
        pass

    # Extract identifiers: camelCase, snake_case, PascalCase — min 4 chars
    tokens = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]{3,}\b', task)
    keywords = [t for t in dict.fromkeys(tokens) if t.lower() not in _STOP_WORDS][:8]

    if not keywords:
        return "".join(parts)

    _EXCLUDE_DIRS = ("node_modules", ".venv", "venv", "__pycache__", ".git",
                     "dist", "build", ".next", "target", ".pytest_cache")

    # Score files by how many keywords they contain
    file_scores: dict[str, int] = {}
    for kw in keywords[:5]:
        try:
            cmd = [
                "grep", "-rl",
                *[f"--include={e}" for e in _CODE_EXTS],
                *[f"--exclude-dir={d}" for d in _EXCLUDE_DIRS],
                kw, ".",
            ]
            result = subprocess.run(
                cmd, cwd=cwd, capture_output=True, text=True,
                encoding="utf-8", errors="replace", timeout=5,
            )
            for path in result.stdout.strip().splitlines():
                file_scores[path] = file_scores.get(path, 0) + 1
        except Exception:
            pass

    # Top-5 most relevant files
    top_files = sorted(file_scores, key=lambda p: -file_scores[p])[:5]
    if not top_files:
        return "".join(parts)

    parts.append("## Relevant local files\n")
    for rel_path in top_files:
        full_path = os.path.join(cwd, rel_path)
        try:
            content = open(full_path, encoding="utf-8", errors="replace").read()
            # Show only lines that contain a keyword (with ±3 lines context)
            snippet = _extract_relevant_lines(content, keywords, max_lines=60)
            entry = f"### {rel_path}\n```\n{snippet}\n```\n\n"
            if total + len(entry) > max_chars:
                break
            parts.append(entry)
            total += len(entry)
        except Exception:
            pass

    return "".join(parts)


def _extract_relevant_lines(content: str, keywords: list[str], max_lines: int = 60) -> str:
    """Return lines containing any keyword with a small window around them."""
    lines = content.splitlines()
    if len(lines) <= max_lines:
        return content

    hit_indices: set[int] = set()
    pat = re.compile("|".join(re.escape(k) for k in keywords), re.IGNORECASE)
    for i, line in enumerate(lines):
        if pat.search(line):
            for j in range(max(0, i - 2), min(len(lines), i + 4)):
                hit_indices.add(j)

    if not hit_indices:
        return "\n".join(lines[:max_lines])

    selected = sorted(hit_indices)[:max_lines]
    result: list[str] = []
    prev = -1
    for idx in selected:
        if prev >= 0 and idx > prev + 1:
            result.append("...")
        result.append(lines[idx])
        prev = idx
    return "\n".join(result)


# ── Run helpers ───────────────────────────────────────────────────────────────

def _pipeline_run(req: RunRequest, config: Any, task_id: str = "") -> dict[str, Any]:
    from voly.catalog.tech_registry import tech_stack_context
    from voly.pipeline import Pipeline

    cfg = config
    if cfg is None:
        from voly.config import load_config
        cfg = load_config()

    pipeline = Pipeline(cfg)
    pipeline.setup_environment()
    run_cwd = os.path.expanduser(req.cwd) if req.cwd else ""
    greenfield = _scaffold_greenfield(run_cwd, req.tech_stack) if run_cwd else False
    _run_auto_reuse(req.task, run_cwd, cfg)
    context: dict[str, Any] = {}
    if run_cwd:
        context["cwd"] = run_cwd

    task = req.task
    if req.tech_stack:
        ctx_block = tech_stack_context(req.tech_stack)
        task = f"{ctx_block}\n\n{task}"
        context["tech_stack"] = req.tech_stack

    try:
        result = pipeline.run(
            task,
            context=context or None,
            force_model=req.model or None,
            force_agent=req.agent or None,
        delegate_to_a2a=req.a2a_delegate,
        task_id=task_id or None,
        )
    finally:
        pipeline.shutdown()

    out: dict[str, Any] = {
        "task_id": task_id,
        "success": result.success,
        "stage": result.stage.value,
        "duration_ms": result.duration_ms,
        "error": result.error,
        "injected_skills": result.injected_skills,
        "skill_suggestions": result.skill_suggestions,
        "tokens_saved_by_rtk": result.tokens_saved_by_rtk,
        "tokens_saved_by_headroom": result.tokens_saved_by_headroom,
        "dspy_used": result.dspy_used,
        "dspy_mode": result.dspy_mode,
        "tech_stack": req.tech_stack or [],
        "greenfield": greenfield,
        **({"project_dir": run_cwd} if greenfield else {}),
    }
    if result.route:
        out["agent"] = result.route.agent
        out["model"] = result.route.model
        out["provider"] = result.route.provider
    if result.response:
        out["content"] = result.response.content
        out["usage"] = {
            "input_tokens": result.response.usage.input_tokens,
            "output_tokens": result.response.usage.output_tokens,
        }
    if result.a2a_tasks:
        out["a2a_tasks"] = [
            {"id": t.id, "state": t.state.value, "agent": t.metadata.get("routed_to", "")}
            for t in result.a2a_tasks
        ]
    ev = result.event
    if ev is not None and getattr(ev, "a2a_dispatched", False):
        out["a2a_dispatched"] = True
        out["a2a_agents_used"] = ev.a2a_agents_used
        out["a2a_assignments"] = ev.a2a_assignments
        assigns = ev.a2a_assignments or []
        exec_n = sum(1 for a in assigns if (a or {}).get("mode") == "executor")
        chat_n = sum(1 for a in assigns if (a or {}).get("mode") == "chat")
        out["hybrid"] = {
            "cwd": run_cwd or getattr(cfg, "default_cwd", "") or "",
            "executor_roles": exec_n,
            "chat_roles": chat_n,
            "files_touched": sorted({
                f
                for a in assigns
                for f in ((a or {}).get("files_touched") or [])
                if f
            }),
        }
    return out


def _executor_run(req: RunRequest, config: Any, task_id: str = "") -> dict[str, Any]:
    from voly.runner.agent_runner import AgentRunner

    cfg = config
    if cfg is None:
        from voly.config import load_config
        cfg = load_config()

    from voly.catalog.tech_registry import tech_stack_context

    work_dir = os.path.expanduser(req.cwd) if req.cwd else os.getcwd()
    greenfield = _scaffold_greenfield(work_dir, req.tech_stack) if req.cwd else False
    _run_auto_reuse(req.task, work_dir if req.cwd else "", cfg)

    # Enrich task with local context for code tasks
    task = req.task
    if req.tech_stack:
        ctx_block = tech_stack_context(req.tech_stack)
        task = f"{ctx_block}\n\n{task}"

    if req.cwd and req.executor not in ("pipeline",):
        ctx = _gather_local_context(req.task, work_dir)
        if ctx:
            task = f"{req.task}\n\n{ctx}"
            _log.info("context gathered: %d chars added to task", len(ctx))

    runner = AgentRunner(cfg)
    result = runner.run(
        task, req.executor, cwd=work_dir,
        max_turns=req.max_turns, timeout=req.timeout, model=req.model or "",
        dry_run=req.dry_run,
        correlation_id=get_correlation_id() or "",
        task_id=task_id,
    )
    meta = result.result.metadata or {}
    out = {
        "success": result.success,
        "executor": result.executor,
        "agent": result.agent,
        "task_id": result.task_id,
        "content": result.result.output or "",
        "error": result.result.error or "",
        "cost_usd": result.result.cost_usd,
        "duration_ms": result.result.duration_ms,
        "num_turns": result.result.num_turns,
        "automation_score": result.automation_score,
        "billing_fallback": meta.get("billing_fallback_to"),
        "chain_timelog": meta.get("chain_timelog"),
        "artifacts": meta.get("artifacts") or [],
    }
    out["tech_stack"] = req.tech_stack or []
    out["greenfield"] = greenfield
    if greenfield:
        out["project_dir"] = work_dir
    if not result.success:
        out.update(executor_failure_details(result.result, executor_name=result.executor))
    # Executor safety policy artifacts (dry-run preview / rollback details).
    for key in ("dry_run", "dry_run_diff", "safety_violation", "safety_rolled_back"):
        if meta.get(key):
            out[key] = meta[key]
    # WorkReport → run report screen (files changed/created/deleted, summary).
    rep = result.result.report
    if rep is not None:
        out["report"] = rep.to_dict() if hasattr(rep, "to_dict") else rep
    return out


def _review_workflow_run(
    req: RunRequest,
    config: Any,
    runs_dir: str,
    workflow_id: str = "",
) -> dict[str, Any]:
    """Run the explicit bounded review workflow for CLI/UI parity."""
    if req.dry_run:
        raise ValueError("review-until-clean does not support dry_run")
    cfg = config
    if cfg is None:
        from voly.config import load_config

        cfg = load_config()

    from voly.catalog.tech_registry import tech_stack_context
    from voly.pipeline import Pipeline
    from voly.runner.agent_runner import AgentRunner
    from voly.runtime.runs import RunTracker
    from voly.telemetry import new_task_id
    from voly.workflow import ReviewUntilClean

    work_dir = os.path.abspath(os.path.expanduser(
        req.cwd or getattr(cfg, "default_cwd", "") or os.getcwd()
    ))
    task = req.task
    if req.tech_stack:
        task = f"{tech_stack_context(req.tech_stack)}\n\n{task}"
    context = _gather_local_context(req.task, work_dir)
    if context:
        task = f"{task}\n\n{context}"

    pipeline = Pipeline(cfg)
    try:
        result = ReviewUntilClean(
            runner=AgentRunner(cfg),
            gateway=pipeline.gateway,
        ).run(
            task,
            cwd=work_dir,
            executor=req.executor if req.executor != "pipeline" else "claude-code",
            max_rounds=req.max_rounds,
            deadline_seconds=req.deadline_seconds,
            executor_timeout=req.timeout,
            max_turns=req.max_turns,
            reviewer_model=req.model,
            tracker=RunTracker(runs_dir),
            workflow_id=workflow_id or new_task_id(),
        )
    finally:
        pipeline.shutdown()
    payload = result.to_dict()
    payload["cost_usd"] = payload["total_cost_usd"]
    payload["cwd"] = work_dir
    return payload


def _needs_executor(task: str, config: Any) -> bool:
    """True when the task requires actual file operations (code gen/edit/fix)."""
    from voly.router import AgentRouter
    router = AgentRouter(config)
    analysis = router.analyze_task(task)
    return analysis.requires_code_gen


def _would_dispatch_a2a(task: str, config: Any) -> bool:
    """True when the pipeline would auto-dispatch this task to the multi-agent path.

    Complex, multi-capability tasks stay in the pipeline (lead orchestrator + sub-agents)
    instead of being promoted to the single-executor claude-code path.
    """
    if config is None:  # --factory mode injects no config → load defaults
        from voly.config import load_config
        config = load_config()
    a2a = getattr(config, "a2a", None)
    if not a2a or not getattr(a2a, "enabled", False) or not getattr(a2a, "auto_dispatch", True):
        return False
    from voly.router import AgentRouter
    analysis = AgentRouter(config).analyze_task(task)
    flags = sum([
        bool(analysis.requires_code_gen),
        bool(analysis.requires_review),
        bool(analysis.requires_testing),
        bool(analysis.requires_deployment),
    ])
    min_flags = getattr(a2a, "min_flags_for_dispatch", 2)
    return flags >= min_flags or getattr(analysis, "complexity", "") == "high"


# ── Main endpoint ─────────────────────────────────────────────────────────────

@router.post("/api/run")
async def run_task(req: RunRequest, request: Request) -> StreamingResponse:
    config = request.app.state.app.config

    async def generate():
        loop = asyncio.get_event_loop()

        # Smart dispatch: pipeline + code task → promote to file-writing executor
        # so the billing fallback chain can kick in; complex tasks stay multi-agent.
        effective_req = req
        start_payload: dict[str, Any] = {
            "task": req.task,
            "executor": req.executor,
            "cwd": req.cwd or "",
            "correlation_id": ensure_correlation_id(),
        }
        if req.workflow:
            start_payload.update({
                "workflow": req.workflow,
                "executor": req.executor if req.executor != "pipeline" else "claude-code",
                "max_rounds": req.max_rounds,
                "deadline_seconds": req.deadline_seconds,
            })
        elif req.executor == "pipeline":
            effective_cwd = (
                req.cwd
                or getattr(config, "default_cwd", "")
                or os.environ.get("VOLY_PROJECT_CWD", "")
                or ""
            )
            try:
                multiagent = await loop.run_in_executor(
                    _THREAD_POOL, _would_dispatch_a2a, req.task, config
                )
                needs_exec = await loop.run_in_executor(
                    _THREAD_POOL, _needs_executor, req.task, config
                )
                if multiagent:
                    if effective_cwd and not req.cwd:
                        effective_req = req.model_copy(update={"cwd": effective_cwd})
                    a2a_cfg = getattr(config, "a2a", None) if config is not None else None
                    cwd_eff = (effective_req.cwd or effective_cwd or "").strip()
                    hybrid_on = bool(getattr(a2a_cfg, "hybrid_code_gen", True)) and bool(cwd_eff)
                    _log.info(
                        "[DISPATCH] pipeline → multi-agent (A2A local)  task=%r  "
                        "hybrid=%s cwd=%r reason=complex_multi_capability",
                        req.task[:60], hybrid_on, cwd_eff[:80] or "(empty)",
                    )
                    start_payload = {
                        "task": effective_req.task,
                        "executor": "pipeline",
                        "a2a": True,
                        "hybrid": hybrid_on,
                        "cwd": cwd_eff,
                    }
                    if bool(getattr(a2a_cfg, "hybrid_code_gen", True)) and not cwd_eff:
                        start_payload["hybrid_warning"] = "hybrid_skipped_no_cwd"
                elif needs_exec:
                    effective_req = req.model_copy(update={
                        "executor": "claude-code",
                        "cwd": effective_cwd,
                    })
                    _log.info(
                        "[DISPATCH] pipeline → claude-code  task=%r  cwd=%r  "
                        "(set VOLY_PROJECT_CWD or cwd field to target project)",
                        req.task[:60], effective_cwd or "(empty — will use server cwd)",
                    )
                    start_payload = {
                        "task": effective_req.task,
                        "executor": "claude-code",
                        "cwd": effective_cwd,
                    }
                else:
                    _log.info(
                        "[DISPATCH] pipeline (text-only)  task=%r  reason=no_code_gen_needed",
                        req.task[:60],
                    )
                    start_payload = {
                        "task": effective_req.task,
                        "executor": "pipeline",
                        "cwd": effective_cwd,
                    }
            except Exception as exc:
                _log.debug("[DISPATCH] auto-promote check failed: %s", exc)

        from voly.runtime.runs import COMPLETED, FAILED, RunTracker
        from voly.telemetry import new_task_id

        run_id = new_task_id()
        runs_dir = str(request.app.state.app.ev_dir.parent / "runs")
        tracker = RunTracker(runs_dir)
        initial_roles = (
            ["developer", "reviewer"]
            if effective_req.workflow == "review-until-clean"
            else [str(start_payload.get("executor") or effective_req.executor or "pipeline")]
        )
        rec = tracker.start(
            run_id,
            effective_req.task,
            initial_roles,
            graph_nodes=[{
                "id": "dispatch",
                "role": "dispatch",
                "status": "running",
                "skills": [],
            }],
        )
        start_payload.update({
            "task_id": run_id,
            "status": rec.status,
            "started_at": rec.started_at,
            "heartbeat_at": rec.heartbeat_at,
            "elapsed_seconds": 0,
            "age_seconds": 0,
            "roles": rec.roles,
            "total_roles": rec.total_roles,
            "done_roles": 0,
            "current_role": rec.current_role,
            "graph_nodes": rec.graph_nodes,
            "graph_edges": rec.graph_edges,
        })
        start_payload["correlation_id"] = ensure_correlation_id()
        yield _sse("start", start_payload)
        try:
            if effective_req.workflow == "review-until-clean":
                future = loop.run_in_executor(
                    _THREAD_POOL,
                    _review_workflow_run,
                    effective_req,
                    config,
                    runs_dir,
                    run_id,
                )
            else:
                fn = _pipeline_run if effective_req.executor == "pipeline" else _executor_run
                future = loop.run_in_executor(
                    _THREAD_POOL, fn, effective_req, config, run_id,
                )
            while True:
                done, _pending = await asyncio.wait({future}, timeout=_RUN_HEARTBEAT_SECONDS)
                if future in done:
                    result = future.result()
                    if isinstance(result, dict):
                        result = {
                            **result,
                            "task_id": run_id,
                            "correlation_id": ensure_correlation_id(),
                        }
                        tracker.finish(
                            run_id,
                            status=COMPLETED if result.get("success") else FAILED,
                            error=str(result.get("error") or ""),
                        )
                    yield _sse("done", result)
                    break
                if await request.is_disconnected():
                    # Python can't force-cancel a blocking subprocess.run() in
                    # the thread pool, so the underlying call still runs to
                    # completion in the background — but there's no client
                    # left to stream to, so stop here instead of holding the
                    # connection (and this generator) open indefinitely.
                    _log.info("[RUN] client disconnected, abandoning SSE stream")
                    return
                yield _sse("heartbeat", {})
        except Exception as exc:
            tracker.finish(run_id, status=FAILED, error=str(exc))
            yield _sse("error", {"error": str(exc)})

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@router.post("/api/tech/detect")
async def detect_tech(req: TechDetectRequest) -> dict:
    """Detect the tech stack implied by a task description.

    When cwd points to a Unity project the exact Editor version is read from
    ProjectSettings/ProjectVersion.txt and used instead of the registry default.
    """
    from voly.catalog.tech_registry import detect_tech_from_task
    detected = detect_tech_from_task(req.task, cwd=req.cwd)
    return {"detected": detected}


@router.get("/api/tech/registry")
async def get_tech_registry() -> dict:
    """Return the full tech registry with all frameworks and current versions."""
    from voly.catalog.tech_registry import get_registry
    return {"registry": get_registry()}


@router.get("/api/tech/categories")
async def get_tech_categories() -> dict:
    """Return project-type categories with pre-resolved tech entries for the fallback picker.

    Used by CategoryPickerModal when tech detection returns nothing — lets the user
    select a project type (web / backend / game / cli / data) to get a relevant
    default tech stack instead of starting blind.
    """
    from voly.catalog.tech_registry import get_categories
    return {"categories": get_categories()}


@router.post("/api/tech/preflight")
async def tech_preflight(req: PreflightRequest) -> dict:
    """Check which requested runtimes are available as system binaries.

    Returns {available: {name: bool}} — only for names that map to a binary.
    Framework-level packages (fastapi, react, pytest) are not checked here;
    they're managed by package managers, not system PATH.
    """
    import shutil
    available = {
        name: shutil.which(_RUNTIME_BINS[name]) is not None
        for name in req.tech
        if name in _RUNTIME_BINS
    }
    return {"available": available}
